openapi: "3.0.3"
info:
    version: "0.0.1"
    title: "WanderSnap API"
    description: This API is used by the WanderSnap iOS App
servers:
    - url: https://api-staging.wandersnap.app/api
      description: Staging Sever
    - url: https://api.wandersnap.app/api
      description: Production Server
paths:
    /ping:
        get:
            tags:
                - Ping
            summary: A ping endpoint to show the API is still running
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Ping"
    /auth/register:
        post:
            tags:
                - Auth
            summary: register for the application
            requestBody:
                $ref: "#/components/requestBodies/RegisterBody"
            responses:
                201:
                    description: Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Register"

    /auth/login:
        post:
            tags:
                - Auth
            summary: register for the application
            requestBody:
                $ref: "#/components/requestBodies/RegisterBody"
            responses:
                "201":
                    description: Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Register"
components:
    securitySchemes:
        bearerAuth: # arbitrary name for the security scheme
            type: http
            scheme: bearer
    schemas:
        Register:
            type: object
            properties:
                token:
                    type: string
        Ping:
            type: object
            properties:
                service:
                    type: string
                    example: "Wandersnap API - Staging"
                timestamp:
                    type: string
                    example: "2023-06-29 06:24:01"

    requestBodies:
        RegisterBody:
            description: The JSON body for the request
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required:
                            - email
                            - password
                            - device_name
                            - name
                        properties:
                            name:
                                type: string
                                example: "Joe Blogs"
                            email:
                                type: string
                                example: "joe@example.com"
                            password:
                                type: string
                                example: "thebestpasswordever"
                            device_name:
                                type: string
                                example: "somedevice"
