openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'WanderSnap API'
  description: This API is used by the WanderSnap iOS App

paths:
  /api/auth/register:
    parameters:
      - name: name
        description: The full name of the user registering to use the application
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/name'
      - name: email
        description: The email address of the user registering to use the application
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/email'
      - name: password
        description: The password of the user registering to use the application
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/email'
    post:
      summary: register for the application
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    name:
      description: The full name of the user
      type: string
    email:
      description: The email address of the user
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []