openapi: '3.0.3'
info:
  version: '0.0.1'
  title: 'WanderSnap API'
  description: This API is used by the WanderSnap iOS App
servers:
  - url: https://api-staging.wandersnap.app/api
    description: Staging Sever
  - url: https://api.wandersnap.app/api
    description: Production Server
paths:
  /auth/register:
    post:
      summary: register for the application
      requestBody:
        $ref: '#/components/requestBodies/RegisterBody'
      responses:
        '201':
          description: The created response when a user is successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'

components:
  schemas:
    Register:
      type: object
      required:
        - email
        - password
        - device_name
        - name
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        device_name:
          type: string
  requestBodies:
    RegisterBody:
      description: The JSON body for the request
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
              - device_name
              - name
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
              device_name:
                type: string