openapi: "3.0.3"
info:
    version: "0.0.1"
    title: "WanderSnap API"
    description: This API is used by the WanderSnap iOS App
servers:
    - url: https://api-staging.wandersnap.app/api
      description: Staging Sever
    - url: https://api.wandersnap.app/api
      description: Production Server
paths:
    /ping:
        get:
            tags:
                - Ping
            summary: A ping endpoint to show the API is still running
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Ping"
    /auth/register:
        post:
            tags:
                - Auth
            summary: register for the application
            requestBody:
                $ref: "#/components/requestBodies/RegisterBody"
            responses:
                201:
                    description: Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Register"

    /auth/login:
        post:
            tags:
                - Auth
            summary: register for the application
            requestBody:
                $ref: "#/components/requestBodies/RegisterBody"
            responses:
                201:
                    description: Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Register"
    /trips:
        get:
            tags:
                - Trips
            summary: returns a list of all the current trips of a user
            responses:
                200:
        post:
            tags:
                - Trips
            responses:
            summary: Creates a new trip

    /trips/{tripId}:
        get:
            parameters:
                - in: path
                  name: tripId
                  required: true
                  schema:
                      type: string
                  description: The trip ID to retrieve
                  example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
                - in: query
                  name: include
                  required: false
                  schema:
                      type: string
                      enum:
                          - owner
                          - image
                  examples:
                      singleInclude:
                          summary: Example of a single include
                          value: "owner"   # ?include=owner
                      multipleIncludes:
                          summary: Example of multiple includes
                          value: "owner,image"   # ?include=owner,image
            tags:
                - Trips
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Trip"
                "401":
                    $ref: '#/components/responses/Unauthorized'
                "403":
                    $ref: '#/components/responses/Forbidden'
                "404":
                    $ref: '#/components/responses/NotFound'

            summary: retrieves a single trip by its ID, this endpoint is scoped to the current user so if a user doesnt own the trip
                    it wont return a trip even if the ID is valid


        delete:
            parameters:
                - in: path
                  name: tripId
                  required: true
                  schema:
                      type: string
                  description: The trip ID to retrieve
                  example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
            tags:
                - Trips
            responses:
                "204":
                    description: The resource was deleted successfully.
                "401":
                    $ref: '#/components/responses/Unauthorized'
                "404":
                    $ref: '#/components/responses/NotFound'
            summary: deletes a users trip

components:
    responses:
        NotFound:
            description: The specified resource was not found
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
        Forbidden:
            description: The specified resource is forbidden
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
        Unauthorized:
            description: Unauthorized
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Error"
    securitySchemes:
        bearerAuth: # arbitrary name for the security scheme
            type: http
            scheme: bearer
    schemas:
        Register:
            type: object
            properties:
                token:
                    type: string
        Ping:
            type: object
            properties:
                service:
                    type: string
                    example: "Wandersnap API - Staging"
                timestamp:
                    type: string
                    example: "2023-06-29 06:24:01"
        Trip:
            type: object
            properties:
                id:
                    type: string
                    example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
                name:
                    type: string
                    example: "South Wales 2023"
                start_date:
                    type: string
                    example: "2023-06-29 06:24:01"
                end_date:
                    type: string
                    example: "2023-06-29 06:24:01"
                cover_photo:
                    type: string
                    example: "/img.jpg"
                created_at:
                    type: string
                    example: "2023-06-29 06:24:01"
                updated_at:
                    type: string
                    example: "2023-06-29 06:24:01"
        Error:
            type: object
            properties:
                code:
                    type: string
                message:
                    type: string
            required:
                - code
                - message
    requestBodies:
        RegisterBody:
            description: The JSON body for the request
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required:
                            - email
                            - password
                            - device_name
                            - name
                        properties:
                            name:
                                type: string
                                example: "Joe Blogs"
                            email:
                                type: string
                                example: "joe@example.com"
                            password:
                                type: string
                                example: "thebestpasswordever"
                            device_name:
                                type: string
                                example: "somedevice"

