openapi: '3.0.0'
info:
  version: '0.0.1'
  title: 'WanderSnap API'
  description: This API is used by the WanderSnap iOS App
servers:
  - url: https://api-staging.wandersnap.app/api
    description: Staging Sever
  - url: https://api.wandersnap.app/api
    description: Production Server
paths:
  /auth/register:
    requestBody:
      $ref: '#/components/requestBodies/RegisterBody'
    post:
      summary: register for the application
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/name'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  requestBodies:
    RegisterBody:
      description: The JSON body for the request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'